chore: add session tracking
getsentry/publish pull request #795
Opened 2022-02-04 18:44 UTC by vladanpaunovic

Add session tracking to enable calculation of release health / crash-free rate in Sentry releases tab.

2022-02-07 11:00 UTC, kamilogorek requested changes

2022-02-07 11:00 UTC, kamilogorek commented on src/publish/fail.js
> +  Sentry.getCurrentHub().endSession(session);
```suggestion
  const session = Sentry.getCurrentHub().startSession({
    release,
    status: "crashed"
  });
  client.captureSession(session);
```

And move release from line 96 to `release` const so we can reuse it in both places. The same change applies to `success.js`.

We could use raw `new Session` here, but its not exported from `@sentry/node`.

2022-02-07 12:25 UTC, kamilogorek approved these changes

2022-02-07 12:26 UTC, kamilogorek approved these changes

2022-02-07 12:26 UTC, kamilogorek approved these changes

2022-02-07 12:26 UTC, kamilogorek approved these changes

2022-02-07 12:27 UTC, kamilogorek approved these changes

2022-02-07 17:27 UTC, merged

2022-02-07 18:35 UTC, AbhiPrasad commented
We've merged in https://github.com/getsentry/sentry-javascript/pull/4508, so we can simplify this code now :)

2022-02-08 09:45 UTC, kamilogorek commented
https://github.com/getsentry/publish/pull/800 👀